# global config
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  TERM: xterm

stages:
  - build

# templates
.cached: &cached
  cache:
    key: "$CI_BUILD_REF_NAME/$CI_BUILD_NAME$CI_PROJECT_DIR"
    paths:
      - build/
  stage: build

.win-artifacts: &win_artifacts
  artifacts:
    paths:
      - build/launcher.exe
      - build/lua53.dll
      - build/neptools-server.dll
      - build/run-tests.exe
      - build/stcm-editor.exe
    when: always

.linux-artifacts: &linux_artifacts
  artifacts:
    paths:
      - build/stcm-editor
      - build/run-tests
    when: always


# builds...
build-clang-msvc-debug:
  <<: *cached
  <<: *win_artifacts
  script:
    - tools/ci.sh clang-msvc debug

build-clang-msvc-rel:
  <<: *cached
  <<: *win_artifacts
  script:
    - tools/ci.sh clang-msvc rel

build-clang-msvc64-debug:
  <<: *cached
  <<: *win_artifacts
  script:
    - tools/ci.sh clang-msvc64 debug

build-clang-msvc64-rel:
  <<: *cached
  <<: *win_artifacts
  script:
    - tools/ci.sh clang-msvc64 rel


build-gcc-amd64-debug:
  <<: *cached
  <<: *linux_artifacts
  script:
    - tools/ci.sh gcc debug

build-gcc-amd64-rel:
  <<: *cached
  <<: *linux_artifacts
  script:
    - tools/ci.sh gcc rel

build-clang-amd64-debug:
  <<: *cached
  <<: *linux_artifacts
  script:
    - tools/ci.sh clang debug

build-clang-amd64-rel:
  <<: *cached
  <<: *linux_artifacts
  script:
    - tools/ci.sh clang rel


binding-gen-test:
  stage: build
  cache:
    paths: [ libshit/ext/ljclang/*.so ]
  script:
    - make -C libshit/ext/ljclang
    - ./gen_binding.sh
    - git diff --submodule=diff --exit-code
  allow_failure: true
